### ISSUE TITLE
how to draw polygon and bounding boxes its not working?

### ISSUE THREAD

**Issue by RajasekharKadasani** [shivs25/angular5-canvas-drawer#1]
free hand polygon and bounding box with image back ground

**Comment by Rlcolli4** [comment]
Please leave us steps in how to recreate this problem. Currently in our implementation of this plug in we can draw polygons and the bounding boxes show up correctly.

**Comment by RajasekharKadasani** [comment]
I just run the app,I selected bounding box button and started drawing but I
can't draw,
There is no option to draw free hand polygon

**Comment by Rlcolli4** [comment]
If you are looking to draw, you need to use one of the buttons listed with a shape (IE "Callout", "Triangle", "Star", etc.), the "Text" button, or the "Pen" button.

The Pen tool allows you to draw polygons with lines, it currently only supports straight lines and does not do curved ones. This is done by clicking to place a point and then moving the mouse and clicking again to make a line. You can complete the shape by drawing the lines until you click on your starting point or you can double click to end the shape open.

The bounding box button changes the bounding box for the entire view, this should be removed as it doesn't actually display any functionality for other users and was used by us for testing purposes.

**Comment by RajasekharKadasani** [comment]
Ok , thank you,
But I expected actual polygon functionality.Becauce we have requirements
for bounding boxes and polygon but both are not working.

**Comment by Rlcolli4** [comment]
In order for us to verify we need the exact steps for how you got this issue. I have loaded up the application and been able to draw lines and polygons using pens and shapes using the shape tools

**Comment by RajasekharKadasani** [comment]
sorry to disturb you,
Actually I downloaded your source and run the app,
Then I selected 'pen','rectangle'.... tried drawing it's working fine.
After I did clear and selected 'bounding box' button ,i am not able to draw
anything.
Please help me on that.

**Comment by Rlcolli4** [comment]
The bounding box button was commented out from the HTML in the last push as, I repeat does not help demonstrate the usefulness of the tool. It was something specific to us in our project. You shouldn't be using it.

**Comment by RajasekharKadasani** [comment]
Oh, actually I also having requirements for my project bounding box and
free hand polygon with closed path,
I implemented in angular is,
Now I am converting to angular 5,so I am asking you much to help

**Comment by Rlcolli4** [comment]
This is how you can test to see if our tool will meet your needs, as this was designed to work with a specific project the functionality can't really be changed at this time.

(1) Draw a shape, open polygon, or polygon using the pen or other tools.
(2) Click "Selector" to change the tool to allow you to manipulate the shapes.
(2) Perform the following actions:
     -Click and hold, move your mouse, and release. This should move the shape to where you let go in the top container.
     -Click the nodes on the corners/sides, hold, and move your mouse then release. This will resize the object contained in that boudning box.

These are the basic, but essential, ways to use our tool. If these do not do what you need to do we are sorry but we can't afford to change the core functionality of the application at this time.

As a side note, if you choose to use the "image" tool and allow users to upload images for it, you will need to write the upload system in your application. The image tool only takes in a image url, it does not handle uploading the image.

**Comment by RajasekharKadasani** [comment]
Thank you for your response,
I looking for different type of functionality,as I am new to angular 5 ,i
asked your help.
Sorry for disturbing you.
