### ISSUE TITLE
How to loaded up the application

### ISSUE THREAD

**Issue by oduvanka** [shivs25/angular5-canvas-drawer#2]
Hi!
I can't have loaded up the application.

My steps:
1) imported DrawerLibraryModule;
_app.module.ts_
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { DrawerLibraryModule } from 'angular5-canvas-drawer';

import { AppComponent } from './app.component';
import { SkyComponent } from './sky/sky.component';

@NgModule({
  declarations: [
    AppComponent,
    SkyComponent
  ],
  imports: [
    BrowserModule,
    DrawerLibraryModule.forRoot()
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
2) create my component;
_app.component.html_
```
<div>
  <p>Drawing constellations</p>
  <app-sky></app-sky>
</div>
```

3)  added the <app-drawer> to my component,added inputs widthValue, heightValue, viewWidthValue, viewTopValue, viewHeightValue, viewLeftValue to my component.
_sky.component.html_
```
<p>sky works!</p>
<app-drawer [widthValue]="width" [heightValue]="height" [viewWidthValue]="viewWidth" [viewTopValue]="viewTop" [viewHeightValue]="viewHeight" [viewLeftValue]="viewLeft"></app-drawer>
```

In the browser console, I see an error:
> Uncaught Error: Template parse errors:
> Can't bind to 'widthValue' since it isn't a known property of 'app-drawer'.
> 1. If 'app-drawer' is an Angular component and it has 'widthValue' input, then verify that it is part of this module.
> 2. If 'app-drawer' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
> 3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("<p>sky works!</p>

What am I doing wrong?
Here is my repository https://github.com/oduvanka/drawing-constellations/tree/master/src/app

**Comment by Rlcolli4** [comment]
Sorry for the slow response, we had to look into this one a little bit. Turns out we forgot to update the usable inputs in our readme.md, it has now been updated. You need to use our `itemViewBox` to set the view. Hopefully this helps!

**Comment by oduvanka** [comment]
Thanks for your answer to my question. I made changes to my component: 

_sky.component.html_
```
<p>sky works!</p>
<app-drawer [itemViewBox]="viewBoxItem"></app-drawer>
```

_sky.component.ts_
```
import { Component, OnInit } from '@angular/core';
import { BoundingBox } from 'angular5-canvas-drawer/lib/build/models/bounding-box';

@Component({
  ...
})
export class SkyComponent implements OnInit {

  public viewBoxItem:BoundingBox;
  ...
}
```

But there is an error in the browser console: 

> Uncaught Error: Template parse errors:
> Can't bind to 'itemViewBox' since it isn't a known property of 'app-drawer'.
> 1. If 'app-drawer' is an Angular component and it has 'itemViewBox' input, then verify that it is part of this module.
> 2. If 'app-drawer' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
> 3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("<p>sky works!</p>
> <app-drawer [ERROR ->][itemViewBox]="viewBoxItem"></app-drawer>"): ng:///AppModule/SkyComponent.html@1:12
>     at syntaxError (compiler.js:2175)
>     at TemplateParser.parse (compiler.js:11388)
>     at JitCompiler._parseTemplate (compiler.js:25963)
>     at JitCompiler._compileTemplate (compiler.js:25951)
>     at compiler.js:25895
>     at Set.forEach (<anonymous>)
>     at JitCompiler._compileComponents (compiler.js:25895)
>     at compiler.js:25808
>     at Object.then (compiler.js:2166)
>     at JitCompiler._compileModuleAndComponents (compiler.js:25807)

Why there was an error?

**Comment by Rlcolli4** [comment]
Hey sorry it took so long to get back to you, had to get a few things sorted out and worked through....

Turns out something in the betas caused issues with the installs, if you had any version installed prior to the one you are using you will need to delete your `package-lock.json` and remove your `node_modules` folder to resolve this. Once you do that, perform a clean npm install and it should solve the issue you mentioned above!
You will also need a few more items to get rolling... 
1. `viewBoxItem` needs to be set, even if its just to `null`. In a future update we will hopefully have this fixed.
2. There are css classes that need to be set on the parent application. If you look at the updated [README.md](https://github.com/shivs25/angular5-canvas-drawer/blob/master/README.md), the bare minimum is defined for you there.

Also version 1.3.0 has been published, it officially has the project converted to Angular 8 if that is of any interest to you.

**Comment by oduvanka** [comment]
> Hey sorry it took so long to get back to you, had to get a few things sorted out and worked through....
> 
> Turns out something in the betas caused issues with the installs, if you had any version installed prior to the one you are using you will need to delete your `package-lock.json` and remove your `node_modules` folder to resolve this. Once you do that, perform a clean npm install and it should solve the issue you mentioned above!
> You will also need a few more items to get rolling...
> 
> 1. `viewBoxItem` needs to be set, even if its just to `null`. In a future update we will hopefully have this fixed.
> 2. There are css classes that need to be set on the parent application. If you look at the updated [README.md](https://github.com/shivs25/angular5-canvas-drawer/blob/master/README.md), the bare minimum is defined for you there.
> 
> Also version 1.3.0 has been published, it officially has the project converted to Angular 8 if that is of any interest to you.

@Rlcolli4 please publish version 1.3.0 on npmjs.com/package/angular5-canvas-drawer

**Comment by Rlcolli4** [comment]
Done. Weird, it said it published when I posted the fix 4 days ago. Seems good now.

**Comment by oduvanka** [comment]
@Rlcolli4 Its ok now)) Thank you very match!)
